version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: test-template-app
    volumes:
      - ./:/code
      - ./node_modules:/node_modules
    working_dir: /code
    ports:
      - 5051:5051
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network  
networks:
  app-network:
    driver: bridge